name: CI

on:
  push:
    branches: [ "gatsby" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.3.1

      - name: Install node packages
        run: yarn
      
      - name: deploy
        run: yarn deploy
